// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtaYmPq8vo2XXtDkWQKIlREr5LHtTsBNY',
    appId: '1:543791710073:web:4d88b3290b1264b81839a8',
    messagingSenderId: '543791710073',
    projectId: 'unimarketyay',
    authDomain: 'unimarketyay.firebaseapp.com',
    storageBucket: 'unimarketyay.firebasestorage.app',
    measurementId: 'G-1QP80ZV87J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9fgZ9tdRyevMsuFizElln3bc9B1BwhgQ',
    appId: '1:543791710073:android:ac9377680598a08c1839a8',
    messagingSenderId: '543791710073',
    projectId: 'unimarketyay',
    storageBucket: 'unimarketyay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFqYV5M-XBbnIzNVM3OjpPFk_aPA7Uwo',
    appId: '1:543791710073:ios:602a9541086794c91839a8',
    messagingSenderId: '543791710073',
    projectId: 'unimarketyay',
    storageBucket: 'unimarketyay.firebasestorage.app',
    iosBundleId: 'com.example.unimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkFqYV5M-XBbnIzNVM3OjpPFk_aPA7Uwo',
    appId: '1:543791710073:ios:602a9541086794c91839a8',
    messagingSenderId: '543791710073',
    projectId: 'unimarketyay',
    storageBucket: 'unimarketyay.firebasestorage.app',
    iosBundleId: 'com.example.unimarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtaYmPq8vo2XXtDkWQKIlREr5LHtTsBNY',
    appId: '1:543791710073:web:6124103cb359ace51839a8',
    messagingSenderId: '543791710073',
    projectId: 'unimarketyay',
    authDomain: 'unimarketyay.firebaseapp.com',
    storageBucket: 'unimarketyay.firebasestorage.app',
    measurementId: 'G-7L43376D1K',
  );

}