name: unimarket
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependency_overrides:
  http: ^1.0.0
  universal_io: ^2.2.0
  uuid: ^3.0.7

dependencies:
  cached_network_image: ^3.2.3
  sqflite: ^2.0.0+3
  speech_to_text: ^5.6.1
  cupertino_progress_bar: ^0.2.0
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.0.6
  algolia: ^1.1.2
  path_provider: ^2.1.1
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1

  # FIREBASE
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4

  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  firebase_performance: ^0.10.1+4
  flutter_launcher_icons: ^0.14.3
  cloud_firestore: ^5.6.5

#Qr code dependencies
  mobile_scanner: ^6.0.7
  pretty_qr_code: ^3.3.0
  firebase_in_app_messaging: ^0.8.1+4
  firebase_storage: ^12.4.4
  uuid: ^4.5.1
  image_picker: ^1.1.2

  #sensor dependencies
  flutter_blue_plus: ^1.35.3 
  permission_handler: ^11.0.1 
  flutter_ble_peripheral: ^1.0.0

  #animations
  flutter_spinkit: ^5.2.1
  camera: ^0.11.1
  arkit_plugin: ^1.1.2
  device_info_plus: ^11.3.0
  vector_math: ^2.1.4
  collection: ^1.19.0
  image_gallery_saver: ^2.0.3
  connectivity_plus: ^6.1.3
  intl: ^0.19.0
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
   
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_icon.png # MAIN ICON
    - assets/svgs/LogoCircle.svg # SVGS
    - assets/svgs/LogoArrows.svg
    - assets/svgs/ImagePlaceHolder.svg 
    - assets/images/LogoSmall.png # IMAGES
    - assets/images/RoundLogo.png
    - assets/images/Avatar.png
    - assets/images/PlainLogoWithBackground.png
    - assets/images/ArrowsLogo.png
    - assets/images/Marketplace.jpg
    - assets/images/Notebooks.png
    - assets/icons/Badge.svg # icons
    - assets/icons/Bell.svg
    - assets/icons/Chat.svg
    - assets/icons/check-heart.svg
    - assets/icons/Explore.svg
    - assets/icons/FindAndOffer.svg
    - assets/icons/Orders.svg
    - assets/icons/Profile.svg
    - assets/icons/Search.svg
    - assets/icons/Shopping Bag Outlined.svg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true